# Generated by Django 4.0.5 on 2022-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
