# Generated by Django 4.0.5 on 2022-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_remove_adverts_category_adverts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
