# Generated by Django 4.0.5 on 2022-06-25 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_category_title_alter_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='image',
            field=models.ImageField(upload_to='advert_foto/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
