# Generated by Django 4.0.5 on 2022-06-25 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_adverts_image_alter_adverts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advert_foto/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
