# Generated by Django 4.0.5 on 2022-06-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_adverts_description_alter_adverts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='adverts.category', verbose_name='Категория'),
        ),
    ]
